_("If you want to allow ftp to read and write files in the user home directories")
_("If you want to allow privoxy to connect to all ports, not just HTTP, FTP, and Gopher ports.")
_("If you want to allow the graphical login program to login directly as sysadm_r:sysadm_t")
_("If you want to allow xen to manage nfs files")
_("If you want to allow confined web browsers to read home directory content")
_("If you want to allow xguest users to configure Network Manager and connect to apache ports")
_("If you want to allow database admins to execute DML statement")
_("If you want to allow tftp to modify public files used for public file transfer services.")
_("If you want to allow direct login to the console device. Required for System 390")
_("If you want to allow user spamassassin clients to use the network.")
_("If you want to allow httpd to act as a relay")
_("If you want to allow openvpn to read home directories")
_("If you want to allow usage of the gpg-agent --write-env-file option. This also allows gpg-agent to manage user files.")
_("If you want to allow the Telepathy connection managers to connect to any generic TCP port.")
_("If you want to allow unconfined users to transition to the Mozilla plugin domain when running xulrunner plugin-container.")
_("If you want to allow confined virtual guests to read fuse files")
_("If you want to allow HTTPD scripts and modules to connect to databases over the network.")
_("If you want to allow users to connect to the local mysql server")
_("If you want to allow user processes to change their priority")
_("If you want to allow ftp servers to login to local users and read/write all files on the system, governed by DAC.")
_("If you want to allow httpd to run gpg in gpg-web domain")
_("If you want to allow samba to act as the domain controller, add users, groups and change passwords.")
_("If you want to allow httpd to execute cgi scripts")
_("If you want to allow confined virtual guests to manage nfs files")
_("If you want to allow all daemons the ability to read/write terminals")
_("If you want to allow confined virtual guests to use serial/parallel communication ports")
_("If you want to allow samba to modify public files used for public file transfer services.  Files/Directories must be labeled public_content_rw_t.")
_("If you want to allow rsync to run as a client")
_("If you want to allow rgmanager domain to connect to the network using TCP.")
_("If you want to allow exim to read unprivileged user files.")
_("If you want to support NFS home directories")
_("If you want to allow Puppet client to manage all file types.")
_("If you want to allow internal-sftp to read and write files in the user ssh home directories.")
_("If you want to allow ssh logins as sysadm_r:sysadm_t")
_("If you want to allow unconfined users to transition to the nsplugin domains when running nspluginviewer")
_("If you want to allow Git daemon system to access cifs file systems.")
_("If you want to allow tor daemon to bind tcp sockets to all unreserved ports.")
_("If you want to allow host key based authentication")
_("If you want to allow httpd to access cifs file systems")
_("If you want to allow piranha-lvs domain to connect to the network using TCP.")
_("If you want to disallow programs, such as newrole, from transitioning to administrative user domains.")
_("If you want to allow Apache to use mod_auth_pam")
_("If you want to allow pppd to be run for a regular user")
_("If you want to allow samba to share any file/directory read only.")
_("If you want to allow ftp servers to use connect to mysql database")
_("If you want to allow Git daemon system to search home directories.")
_("If you want to support SAMBA home directories")
_("If you want to allow users to login using a sssd server")
_("If you want to allow samba to create new home directories (e.g. via PAM)")
_("If you want to control users use of ping and traceroute")
_("If you want to allow ftp servers to use cifs used for public file transfer services.")
_("If you want to allow the Irssi IRC Client to connect to any port, and to bind to any unreserved port.")
_("If you want to allow ftp servers to use nfs used for public file transfer services.")
_("If you want to allow httpd to read home directories")
_("If you want to allow gpg web domain to modify public files used for public file transfer services.")
_("If you want to allow rsync to export any files/directories read only.")
_("If you want to allow all unconfined executables to use libraries requiring text relocation that are not labeled textrel_shlib_t")
_("If you want to allow apache scripts to write to public content.  Directories/Files must be labeled public_rw_content_t.")
_("If you want to allow qemu to use cifs/Samba file systems")
_("If you want to allow qemu to use serial/parallel communication ports")
_("If you want to allow Apache to communicate with avahi service via dbus")
_("If you want to allow dhcpc client applications to execute iptables commands")
_("If you want to allow samba to share users home directories.")
_("If you want to enable reading of urandom for all domains.")
_("If you want to allow racoon to read shadow")
_("If you want to allow Cobbler to connect to the network using TCP.")
_("If you want to allow squid to run as a transparent proxy (TPROXY)")
_("If you want to prevent all confined domains from loading policy, setting enforcing mode, and changing boolean values.  Set this to true and you have to reboot to set it back")
_("If you want to allow unconfined executables to make their heap memory executable.  Doing this is a really bad idea. Probably indicates a badly coded executable, but could indicate an attack. This executable should be reported in bugzilla")
_("If you want to allow dbadm to manage files in users home directories")
_("If you want to allow confined virtual guests to interact with the xserver")
_("If you want to transition to confined qemu domains from unconfined user")
_("If you want to allow Git daemon system to access nfs file systems.")
_("If you want to unify HTTPD handling of all content files.")
_("If you want to allow nsplugin code to connect to unreserved ports")
_("If you want to allow rsync to modify public files used for public file transfer services.  Files/Directories must be labeled public_content_rw_t.")
_("If you want to allow qemu to use nfs file systems")
_("If you want to allow HTTPD scripts and modules to connect to the network using any TCP port.")
_("If you want to allow qemu to use usb devices")
_("If you want to allow exim to connect to databases (postgres, mysql)")
_("If you want to allow unconfined executables to map a memory region as both executable and writable, this is dangerous and the executable should be reported in bugzilla")
_("If you want to allow varnishd to connect to all ports, not just HTTP.")
_("If you want to allow mplayer executable stack")
_("If you want to allow httpd scripts and modules execmem/execstack")
_("If you want to allow all daemons to write corefiles to /")
_("If you want to allow cdrecord to read various content. nfs, samba, removable devices, user temp and untrusted content files")
_("If you want to allow confined virtual guests to manage device configuration, (pci)")
_("If you want to allow spamd to read/write user home directories.")
_("If you want to allow Apache to use mod_auth_ntlm_winbind")
_("If you want to allow the graphical login program to execute bootloader")
_("If you want to allow system to run with NIS")
_("If you want to allow qemu to connect fully to the network")
_("If you want to allow unconfined executables to make their stack executable.  This should never, ever be necessary. Probably indicates a badly coded executable, but could indicate an attack. This executable should be reported in bugzilla")
_("If you want to unify HTTPD to communicate with the terminal. Needed for entering the passphrase for certificates at the terminal.")
_("If you want to allow sftp-internal to read and write files in the user home directories")
_("If you want to support fusefs home directories")
_("If you want to allow confined applications to use nscd shared memory.")
_("If you want to allow w to display everyone")
_("If you want to allow Apache to modify public files used for public file transfer services. Directories/Files must be labeled public_content_rw_t.")
_("If you want to allow dbadm to read files in users home directories")
_("If you want to allow regular users direct dri device access")
_("If you want to allow the mount command to mount any directory or file.")
_("If you want to allow a user to login as an unconfined domain")
_("If you want to disallow programs and users from transitioning to insmod domain.")
_("If you want to allow Cobbler to access nfs file systems.")
_("If you want to allow nsplugin code to execmem/execstack")
_("If you want to allows clients to write to the X server shared memory segments.")
_("If you want to allow webadm to read files in users home directories")
_("If you want to enable polyinstantiated directory support.")
_("If you want to support X userspace object manager")
_("If you want to ignore vbetool mmap_zero errors.")
_("If you want to allow httpd to read user content")
_("If you want to allow httpd to access nfs file systems")
_("If you want to allow postfix_local domain full write access to mail_spool directories")
_("If you want to allow xguest users to use blue tooth devices")
_("If you want to use lpd server instead of cups")
_("If you want to allow Apache to execute tmp content.")
_("If you want to allow user to r/w files on filesystems that do not have extended attributes (FAT, CDROM, FLOPPY)")
_("If you want to allow users to run TCP servers (bind to ports and accept connection from the same domain and outside users)  disabling this forces FTP passive mode and may change other protocols.")
_("If you want to allow mysqld to connect to all ports")
_("If you want to allow regular users direct mouse access")
_("If you want to allow all domains to have the kernel load modules")
_("If you want to allow confined virtual guests to use usb devices")
_("If you want to enable additional permissions needed to support devices on 3ware controllers.")
_("If you want to allow ABRT to modify public files used for public file transfer services.")
_("If you want to allow java executable stack")
_("If you want to allow http daemon to send mail")
_("If you want to allow samba to export ntfs/fusefs volumes.")
_("If you want to enable support for upstart as the init program.")
_("If you want to allow sshd to forward port connections")
_("If you want to allow zebra daemon to write it configuration files")
_("If you want to allow httpd to use built in scripting (usually php)")
_("If you want to allow exim to create, read, write, and delete unprivileged user files.")
_("If you want to allow Cobbler to modify public files used for public file transfer services.")
_("If you want to allow samba to export NFS volumes.")
_("If you want to control the ability to mmap a low area of the address space, as configured by /proc/sys/kernel/mmap_min_addr.")
_("If you want to ignore wine mmap_zero errors.")
_("If you want to allow sysadm to debug or ptrace all processes.")
_("If you want to allow logging in and using the system from /dev/console.")
_("If you want to allow fenced domain to connect to the network using TCP.")
_("If you want to allow users to connect to PostgreSQL")
_("If you want to allow cvs daemon to read shadow")
_("If you want to allow http daemon to check spam")
_("If you want to allow sftp-internal to login to local users and read/write all files on the system, governed by DAC.")
_("If you want to allow xguest users to mount removable media")
_("If you want to allow icecast to connect to all ports, not just sound ports.")
_("If you want to allow pppd to load kernel modules for certain modems")
_("If you want to allow samba to run unconfined scripts")
_("If you want to allow confined applications to run with kerberos.")
_("If you want to allow httpd to connect to memcache server")
_("If you want to allow HTTPD scripts and modules to connect to cobbler over the network.")
_("If you want to allow sasl to read shadow")
_("If you want to allow ftp servers to upload files,  used for public file transfer services. Directories must be labeled public_content_rw_t.")
_("If you want to allow vidio playing tools to tun unconfined")
_("If you want to allow gssd to read temp directory.  For access to kerberos tgt.")
_("If you want to allow webadm to manage files in users home directories")
_("If you want to allow clamd to use JIT compiler")
_("If you want to allows XServer to execute writable memory")
_("If you want to allow Git daemon session to bind tcp sockets to all unreserved ports.")
_("If you want to allow HTTPD to run SSI executables in the same domain as system CGI scripts.")
_("If you want to allow samba to share any file/directory read/write.")
_("If you want to allow Puppet master to use connect to mysql and postgresql database")
_("If you want to allow httpd to act as a FTP server by listening on the ftp port.")
_("If you want to enable extra rules in the cron domain to support fcron.")
_("If you want to allow nfs servers to modify public files used for public file transfer services.  Files/Directories must be labeled public_content_rw_t.")
_("If you want to allow any files/directories to be exported read/write via NFS.")
_("If you want to allow all domains to use other domains file descriptors")
_("If you want to allow users to login using a radius server")
_("If you want to allow Cobbler to access cifs file systems.")
_("If you want to allow httpd daemon to change system limits")
_("If you want to allow squid to connect to all ports, not just HTTP, FTP, and Gopher ports.")
_("If you want to allow users to read system messages.")
_("If you want to allow confined virtual guests to manage cifs files")
_("If you want to enable support for systemd as the init program.")
_("If you want to allow BIND to write the master zone files. Generally this is used for dynamic DNS or zone transfers.")
_("If you want to allow any files/directories to be exported read/only via NFS.")
_("If you want to allow system cron jobs to relabel filesystem for restoring file contexts.")
_("If you want to allow anon internal-sftp to upload files, used for public file transfer services. Directories must be labeled public_content_rw_t.")
_("If you want to allow unprived users to execute DDL statement")
