.TH seapplet "1" "2 July 2019"

.SH NAME
seapplet \- setroubleshoot client GUI applet
.SH SYNOPSIS
.B seapplet

.SH DESCRIPTION
.B seapplet
is a GTK\(hybased GUI applet designed to notify users of new SELinux alerts
and open sealert to assist with their resolution. Seapplet is normally
started at login by the desktop session manager and does not need to be executed
manually. In order to function properly, seapplet requires that the desktop
environment provides a System Tray implementation in which the applet will be 
embedded.

.SH SEE ALSO
.BR sealert (8),
.BR setroubleshootd (8),
.BR sedispatch (8),
.BR selinux (8).